org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=128m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=2
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=false
# Flutter migratorにより追加されたBuilt-in Kotlin無効化フラグ
android.builtInKotlin=false
# Flutter migratorにより追加された新DSL無効化フラグ
android.newDsl=false
