// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBuzpcHBaJiAQ4FQo5Ifa9lDzCx7w4HU',
    appId: '1:84109084305:web:7cc658d25f8e76452ae130',
    messagingSenderId: '84109084305',
    projectId: 'utopian-bonito-461312-r2',
    authDomain: 'utopian-bonito-461312-r2.firebaseapp.com',
    storageBucket: 'utopian-bonito-461312-r2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmo_4JQQXtIxWfTkQ9iYCVvps9hJ-LlU',
    appId: '1:84109084305:android:cbd4e57369a602962ae130',
    messagingSenderId: '84109084305',
    projectId: 'utopian-bonito-461312-r2',
    storageBucket: 'utopian-bonito-461312-r2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1X9mpxokFa2yPxnAfC0jCB7_tRua19lI',
    appId: '1:84109084305:ios:197e8e848eae94472ae130',
    messagingSenderId: '84109084305',
    projectId: 'utopian-bonito-461312-r2',
    storageBucket: 'utopian-bonito-461312-r2.firebasestorage.app',
    iosBundleId: 'com.example.flutterVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1X9mpxokFa2yPxnAfC0jCB7_tRua19lI',
    appId: '1:84109084305:ios:197e8e848eae94472ae130',
    messagingSenderId: '84109084305',
    projectId: 'utopian-bonito-461312-r2',
    storageBucket: 'utopian-bonito-461312-r2.firebasestorage.app',
    iosBundleId: 'com.example.flutterVerification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzBuzpcHBaJiAQ4FQo5Ifa9lDzCx7w4HU',
    appId: '1:84109084305:web:a2c4b81e5a9541be2ae130',
    messagingSenderId: '84109084305',
    projectId: 'utopian-bonito-461312-r2',
    authDomain: 'utopian-bonito-461312-r2.firebaseapp.com',
    storageBucket: 'utopian-bonito-461312-r2.firebasestorage.app',
  );

}