// Mocks generated by Mockito 5.4.6 from annotations
// in memora/test/application/usecases/get_groups_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:memora/domain/entities/group.dart' as _i4;
import 'package:memora/domain/repositories/group_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i2.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Group>> getGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getGroups, []),
            returnValue: _i3.Future<List<_i4.Group>>.value(<_i4.Group>[]),
          )
          as _i3.Future<List<_i4.Group>>);

  @override
  _i3.Future<void> saveGroup(_i4.Group? group) =>
      (super.noSuchMethod(
            Invocation.method(#saveGroup, [group]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroup, [groupId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Group?> getGroupById(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupById, [groupId]),
            returnValue: _i3.Future<_i4.Group?>.value(),
          )
          as _i3.Future<_i4.Group?>);
}
