// Mocks generated by Mockito 5.4.6 from annotations
// in memora/test/unit/application/usecases/get_or_create_member_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:memora/domain/entities/member.dart' as _i4;
import 'package:memora/domain/repositories/member_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i2.MemberRepository {
  MockMemberRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Member>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i3.Future<List<_i4.Member>>.value(<_i4.Member>[]),
          )
          as _i3.Future<List<_i4.Member>>);

  @override
  _i3.Future<void> saveMember(_i4.Member? member) =>
      (super.noSuchMethod(
            Invocation.method(#saveMember, [member]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMember(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMember, [memberId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Member?> getMemberById(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberById, [memberId]),
            returnValue: _i3.Future<_i4.Member?>.value(),
          )
          as _i3.Future<_i4.Member?>);

  @override
  _i3.Future<_i4.Member?> getMemberByAccountId(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberByAccountId, [accountId]),
            returnValue: _i3.Future<_i4.Member?>.value(),
          )
          as _i3.Future<_i4.Member?>);
}
