// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_verification/test/application/load_pins_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_verification/domain/pin.dart' as _i5;
import 'package:flutter_verification/infrastructure/pin_repository.dart' as _i2;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PinRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPinRepository extends _i1.Mock implements _i2.PinRepository {
  MockPinRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePin(_i4.LatLng? position) =>
      (super.noSuchMethod(
            Invocation.method(#savePin, [position]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Pin>> getPins() =>
      (super.noSuchMethod(
            Invocation.method(#getPins, []),
            returnValue: _i3.Future<List<_i5.Pin>>.value(<_i5.Pin>[]),
          )
          as _i3.Future<List<_i5.Pin>>);
}
