// Mocks generated by Mockito 5.4.6 from annotations
// in memora/test/unit/application/usecases/trip/fetch_route_info_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:memora/core/enums/travel_mode.dart' as _i6;
import 'package:memora/domain/services/route_info_service.dart' as _i3;
import 'package:memora/domain/value_objects/location.dart' as _i5;
import 'package:memora/domain/value_objects/route_segment_detail.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRouteSegmentDetail_0 extends _i1.SmartFake
    implements _i2.RouteSegmentDetail {
  _FakeRouteSegmentDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouteInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteInfoService extends _i1.Mock implements _i3.RouteInfoService {
  MockRouteInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RouteSegmentDetail> fetchRoute({
    required _i5.Location? origin,
    required _i5.Location? destination,
    required _i6.TravelMode? travelMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoute, [], {
              #origin: origin,
              #destination: destination,
              #travelMode: travelMode,
            }),
            returnValue: _i4.Future<_i2.RouteSegmentDetail>.value(
              _FakeRouteSegmentDetail_0(
                this,
                Invocation.method(#fetchRoute, [], {
                  #origin: origin,
                  #destination: destination,
                  #travelMode: travelMode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.RouteSegmentDetail>);
}
